name: dummy-svc

on: [push]
        
jobs:
    Build:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4
        
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - run: |
            docker build . -t fitrakz/prometheus_dummy:0.0.2
            docker push fitrakz/prometheus_dummy:0.0.2